/*
  # Global Pipeline Network Expansion

  ## Purpose
  Adds comprehensive global oil, gas, and LNG pipeline infrastructure covering all major
  regions: Middle East, Russia/FSU, Europe, North America, Africa, Asia-Pacific, South America,
  and Central Asia. Each entry represents a major trunk pipeline with its route midpoint
  coordinates, capacity, status, and known incident history.

  ## Changes
  - New rows in `critical_infrastructure` table (infra_type = 'pipeline')
  - Covers ~130+ additional major pipelines worldwide
  - All statuses set appropriately (intact/damaged/destroyed)

  ## Notes
  1. Coordinates represent approximate route midpoints or key facilities
  2. Existing Middle East pipeline entries are NOT duplicated
  3. No DDL changes — data-only migration
*/

INSERT INTO critical_infrastructure (name, country, region, infra_type, status, latitude, longitude, description, last_incident_date, incident_notes, source_url) VALUES

-- ======================================================
-- RUSSIA & FORMER SOVIET UNION
-- ======================================================
('Druzhba Pipeline (Friendship Pipeline)', 'Russia', 'Europe', 'pipeline', 'damaged', 53.9000, 32.0000, 'World''s longest oil pipeline, 5,500km. Carries Russian crude from Siberia to Central/Eastern Europe via Belarus and Ukraine. 1.2 million bpd capacity.', '2022-04-25', 'Poland, Germany, Czech Republic halted imports following Russia''s invasion of Ukraine 2022. Southern branch still flows to Hungary, Slovakia. Contamination incident 2019 polluted pipeline across multiple countries.', 'https://en.wikipedia.org/wiki/Druzhba_pipeline'),
('Nord Stream 1 Gas Pipeline', 'Russia', 'Europe', 'pipeline', 'destroyed', 55.5000, 15.0000, 'Twin offshore gas pipelines running 1,224km under Baltic Sea from Vyborg, Russia to Lubmin, Germany. 55 bcm/year capacity. Completed 2011.', '2022-09-26', 'Both Nord Stream 1 pipelines deliberately sabotaged by underwater explosions September 2022 in what NATO called unprecedented infrastructure attack. Investigation ongoing; multiple suspects including Ukraine and US-linked operatives cited.', 'https://en.wikipedia.org/wiki/Nord_Stream'),
('Nord Stream 2 Gas Pipeline', 'Russia', 'Europe', 'pipeline', 'destroyed', 55.3000, 14.5000, 'Parallel Baltic Sea offshore pipeline, twin of Nord Stream 1. Completed 2021 but never put into commercial operation due to German certification halt.', '2022-09-26', 'One of two pipelines destroyed in September 2022 coordinated sabotage attack alongside Nord Stream 1. Never operational. Formally abandoned 2024.', 'https://en.wikipedia.org/wiki/Nord_Stream_2'),
('TurkStream Gas Pipeline', 'Russia', 'Europe', 'pipeline', 'intact', 42.0000, 30.0000, 'Offshore gas pipeline from Anapa, Russia across Black Sea to Turkey. 31.5 bcm/year. Two lines: one for Turkey, one for Southeast Europe.', '', 'Operational since 2020. Key route for Russian gas to Southern Europe bypassing Ukraine. Still operational despite sanctions.', 'https://en.wikipedia.org/wiki/TurkStream'),
('Blue Stream Gas Pipeline', 'Russia', 'Europe', 'pipeline', 'intact', 42.5000, 35.0000, 'Offshore gas pipeline under Black Sea from Izobilnoye, Russia to Samsun, Turkey. 16 bcm/year.', '', 'Operational since 2003. Supplemented by TurkStream. Still flowing.', 'https://en.wikipedia.org/wiki/Blue_Stream'),
('Urengoy-Pomary-Uzhhorod Pipeline (Brotherhood)', 'Russia', 'Europe', 'pipeline', 'damaged', 50.0000, 30.0000, 'Major Soviet-era gas pipeline carrying Siberian gas through Ukraine to Slovakia and Western Europe. 26 bcm/year (reduced).', '2024-01-01', 'Ukraine allowed 5-year transit agreement to expire January 1 2025, ending Russian gas flows through Ukraine to Slovakia, Austria, Hungary.', 'https://en.wikipedia.org/wiki/Urengoy%E2%80%93Pomary%E2%80%93Uzhhorod_pipeline'),
('Power of Siberia Gas Pipeline (China-Russia)', 'Russia', 'East Asia', 'pipeline', 'intact', 52.0000, 122.0000, 'New 3,000km gas pipeline from Siberian Chayanda field to China''s northeastern border. 38 bcm/year at full capacity.', '', 'Operational since December 2019. Russia''s main gas export route to China as European markets close. Capacity being expanded.', 'https://en.wikipedia.org/wiki/Power_of_Siberia'),
('Power of Siberia 2 (Planned)', 'Russia', 'East Asia', 'pipeline', 'intact', 52.0000, 98.0000, 'Proposed 6,700km pipeline through Mongolia to China. 50 bcm/year planned capacity. Russia''s largest planned gas infrastructure.', '', 'Under negotiation as of 2024. Not yet constructed. Russia pushing for deal amid European gas isolation.', 'https://en.wikipedia.org/wiki/Power_of_Siberia_2'),
('Yamal-Europe Gas Pipeline', 'Russia', 'Europe', 'pipeline', 'intact', 52.5000, 16.0000, 'Gas pipeline from Yamal Peninsula in Siberia through Belarus and Poland to Germany. 33 bcm/year.', '2021-11-11', 'Russia reversed flow westward to eastward (back toward Russia) for several days in November 2021 amid gas price crisis. Now reduced flows.', 'https://en.wikipedia.org/wiki/Yamal%E2%80%93Europe_pipeline'),
('Sakhalin-Khabarovsk-Vladivostok Gas Pipeline', 'Russia', 'East Asia', 'pipeline', 'intact', 49.0000, 141.0000, 'Pipeline carrying Sakhalin gas down Russian Pacific coast to Vladivostok. 6.2 bcm/year.', '', 'Operational since 2011. Supplies Russian Far East domestic market and potential LNG exports.', ''),
('Tengiz-Novorossiysk Pipeline (CPC)', 'Kazakhstan', 'Central Asia', 'pipeline', 'intact', 45.5000, 52.0000, 'Caspian Pipeline Consortium. Carries Kazakh crude from Tengiz field to Black Sea port of Novorossiysk. 1.5 million bpd.', '2022-03-22', 'Technical failures at Novorossiysk marine terminal disrupted exports for weeks March 2022. Russia cited storm damage; widely seen as political pressure. Flows restored.', 'https://en.wikipedia.org/wiki/Caspian_Pipeline_Consortium'),
('Kazakhstan-China Oil Pipeline', 'Kazakhstan', 'Central Asia', 'pipeline', 'intact', 44.0000, 68.0000, 'Pipeline from Atyrau, Kazakhstan via Kenkiyak to Alashankou, China. 400,000 bpd. 2,228km.', '', 'Operational since 2006. China''s main oil import route from Central Asia.', 'https://en.wikipedia.org/wiki/Kazakhstan%E2%80%93China_oil_pipeline'),
('Trans-Caspian Gas Pipeline (Proposed)', 'Kazakhstan', 'Central Asia', 'pipeline', 'intact', 42.5000, 52.0000, 'Proposed pipeline crossing Caspian Sea from Turkmenistan/Kazakhstan to Azerbaijan. Key to bypassing Russia.', '', 'Repeatedly blocked by Russia and Iran citing legal status of Caspian. EU actively pushing for construction.', ''),
('Central Asia-China Gas Pipeline (CAGP)', 'Turkmenistan', 'Central Asia', 'pipeline', 'intact', 38.5000, 63.5000, 'Four parallel pipelines (A,B,C,D) carrying Turkmen gas to China. Total 85 bcm/year. Longest gas pipeline network in world.', '', 'Operational since 2009-2022. China''s largest gas import source. Bypasses Russia entirely.', 'https://en.wikipedia.org/wiki/Central_Asia%E2%80%93China_gas_pipeline'),
('Trans-Afghan Pipeline (TAPI)', 'Turkmenistan', 'South Asia', 'pipeline', 'intact', 35.0000, 63.0000, 'Proposed pipeline from Turkmenistan through Afghanistan, Pakistan to India. 33 bcm/year planned. 1,814km.', '', 'Construction started 2018 in Turkmenistan section; halted due to Afghan security concerns. Taliban control since 2021 complicated project.', 'https://en.wikipedia.org/wiki/Trans-Afghanistan_Pipeline'),

-- ======================================================
-- EUROPE
-- ======================================================
('Trans-Mediterranean Pipeline (Transmed)', 'Tunisia', 'Europe', 'pipeline', 'intact', 37.0000, 11.0000, 'Carries Algerian gas across Tunisia and under Mediterranean to Italy. 33 bcm/year. 2,475km. Operational since 1983.', '', 'Still operational. Key Algerian gas export to Italy and Europe.', 'https://en.wikipedia.org/wiki/Transmed_pipeline'),
('Medgaz Pipeline (Algeria-Spain)', 'Algeria', 'Europe', 'pipeline', 'damaged', 36.5000, 1.5000, 'Offshore pipeline carrying Algerian gas directly to Spain under Mediterranean. 8 bcm/year.', '2021-10-31', 'Algeria cut off gas flows through Morocco''s Maghreb-Europe pipeline after diplomatic rupture with Morocco Oct 2021. Medgaz capacity being expanded to compensate.', 'https://en.wikipedia.org/wiki/Medgaz'),
('Maghreb-Europe Gas Pipeline (GME)', 'Morocco', 'Europe', 'pipeline', 'intact', 34.0000, -4.0000, 'Carries Algerian gas through Morocco to Spain/Portugal. 13.5 bcm/year. Flows cut by Algeria-Morocco dispute 2021.', '2021-10-31', 'Algeria halted gas flows through this pipeline after cutting diplomatic relations with Morocco. Reversed to carry Spanish gas to Morocco.', 'https://en.wikipedia.org/wiki/Maghreb%E2%80%93Europe_Gas_Pipeline'),
('TAP (Trans Adriatic Pipeline)', 'Greece', 'Europe', 'pipeline', 'intact', 40.5000, 22.5000, 'Carries Azerbaijani gas from Greek-Turkish border through Greece, Albania, under Adriatic to Italy. 10 bcm/year. Final leg of Southern Gas Corridor.', '', 'Operational since 2021. Key diversification route for EU gas from Azerbaijan.', 'https://en.wikipedia.org/wiki/Trans-Adriatic_Pipeline'),
('TANAP (Trans-Anatolian Pipeline)', 'Turkey', 'Middle East', 'pipeline', 'intact', 39.5000, 36.0000, 'Carries Azerbaijani Shah Deniz gas through Turkey 1,850km from Georgian border to Greek border. 16 bcm/year. Part of Southern Gas Corridor.', '', 'Operational since 2018. Key route for Caspian gas to Europe bypassing Russia.', 'https://en.wikipedia.org/wiki/Trans-Anatolian_gas_pipeline'),
('South Caucasus Pipeline (SCP)', 'Azerbaijan', 'Caucasus', 'pipeline', 'intact', 41.0000, 46.0000, 'Carries Shah Deniz gas from Baku area through Georgia to Turkish border. 25 bcm/year (expanded). Part of Southern Gas Corridor.', '', 'Operational since 2006. Critical link in EU gas diversification strategy.', 'https://en.wikipedia.org/wiki/South_Caucasus_Pipeline'),
('IGB (Interconnector Greece-Bulgaria)', 'Greece', 'Europe', 'pipeline', 'intact', 41.5000, 26.0000, 'New pipeline connecting Greek and Bulgarian gas grids. 3 bcm/year (expandable to 5 bcm).', '', 'Completed 2022. Key for carrying Azerbaijani and LNG gas northward into Central/Eastern Europe.', ''),
('Baltic Pipe (Norway-Poland via Denmark)', 'Denmark', 'Europe', 'pipeline', 'intact', 56.5000, 10.0000, 'New offshore pipeline carrying Norwegian North Sea gas through Denmark to Poland. 10 bcm/year.', '', 'Opened October 2022, strategically timed as Nord Stream sabotage occurred simultaneously. Key for Polish gas diversification from Russia.', 'https://en.wikipedia.org/wiki/Baltic_Pipe'),
('Interconnector UK-Belgium (IUK)', 'United Kingdom', 'Europe', 'pipeline', 'intact', 51.5000, 2.5000, 'Offshore pipeline connecting UK and Belgian gas systems. 20 bcm/year bidirectional. Key UK-Europe gas trading link.', '', 'Operational since 1998. Carries Norwegian and UK North Sea gas to Continental Europe and vice versa.', ''),
('Langeled Pipeline (Norway-UK)', 'Norway', 'Europe', 'pipeline', 'intact', 58.0000, 2.0000, 'World''s longest subsea pipeline. Carries Norwegian gas to UK. 25.5 bcm/year. 1,166km from Nyhamna to Easington.', '', 'Operational since 2007. Critical UK gas supply from Norwegian North Sea.', 'https://en.wikipedia.org/wiki/Langeled_pipeline'),
('Franpipe (Norway-France)', 'Norway', 'Europe', 'pipeline', 'intact', 57.5000, 3.5000, 'Offshore pipeline from Draupner platform to Dunkirk, France. 17 bcm/year.', '', 'Operational since 1998. Part of Norwegian gas export network to continental Europe.', ''),
('EUGAL/OPAL Pipeline (Germany)', 'Germany', 'Europe', 'pipeline', 'intact', 52.5000, 13.5000, 'German onshore pipeline receiving Russian gas from Nord Stream 1 and distributing to Central Europe. Now repurposed.', '', 'Nord Stream 1 sabotage effectively idled these pipelines. Being repurposed for LNG import distribution from German LNG terminals.', ''),
('WAG Pipeline (West Austria Gas)', 'Austria', 'Europe', 'pipeline', 'intact', 48.0000, 15.0000, 'Transit pipeline carrying Russian gas through Austria to Italy. Major European transit route.', '2022-11-01', 'Significantly reduced flows following Russia sanctions. Austria was last major EU importer of Russian gas until late 2024.', ''),
('TAG Pipeline (Trans-Austria Gas)', 'Austria', 'Europe', 'pipeline', 'intact', 47.0000, 14.5000, 'Main transit pipeline for Russian gas through Austria to Italy. 40 bcm/year capacity.', '2024-12-31', 'Major flows ceased when Ukraine-Russia transit agreement expired end of 2024. Austria secured alternative supplies.', 'https://en.wikipedia.org/wiki/Trans-Austria_Gas_Pipeline'),
('GIPL (Gas Interconnection Poland-Lithuania)', 'Lithuania', 'Europe', 'pipeline', 'intact', 54.5000, 23.5000, 'First gas pipeline directly connecting Baltic states to continental European gas grid. 2.4 bcm/year. Completed 2022.', '', 'Operational since May 2022. Allows Baltic states to fully end dependency on Russian gas via Finland/Estonia LNG.', ''),
('EastMed Pipeline (Proposed)', 'Cyprus', 'Middle East', 'pipeline', 'intact', 34.5000, 32.0000, 'Proposed 1,900km pipeline carrying Eastern Mediterranean gas from Israel/Cyprus to Greece and Italy. 10 bcm/year.', '', 'Project paused 2022 after US withdrew support. Economics challenged by LNG alternatives. Still discussed politically.', 'https://en.wikipedia.org/wiki/EastMed_pipeline'),

-- ======================================================
-- NORTH AMERICA
-- ======================================================
('Trans-Alaska Pipeline System (TAPS)', 'United States', 'North America', 'pipeline', 'intact', 65.5000, -153.0000, 'Carries oil from Prudhoe Bay on North Slope to Valdez terminal, Alaska. 800 miles. 0.5 million bpd (declining from peak 2.1 mbpd).', '2001-10-04', 'Shot by gunman 2001, causing spill. Multiple operational incidents over decades. Climate change threatening permafrost stability under pipeline supports.', 'https://en.wikipedia.org/wiki/Trans-Alaska_Pipeline_System'),
('Keystone Pipeline System', 'United States', 'North America', 'pipeline', 'intact', 45.0000, -98.0000, 'Carries Canadian oil sands crude from Alberta to US Midwest and Gulf Coast refineries. 590,000 bpd (existing system).', '2023-12-07', 'Major spill 14,000 barrels in North Dakota December 2023. Keystone XL extension cancelled by Biden administration 2021.', 'https://en.wikipedia.org/wiki/Keystone_Pipeline'),
('Colonial Pipeline System', 'United States', 'North America', 'pipeline', 'intact', 35.0000, -82.0000, 'Largest US refined products pipeline. Carries gasoline, diesel, jet fuel from Gulf Coast refineries to Southeast and Northeast US. 2.5 million bpd.', '2021-05-07', 'DarkSide ransomware attack shut down pipeline for 6 days May 2021, causing fuel shortages across US East Coast. Largest cyberattack on US infrastructure.', 'https://en.wikipedia.org/wiki/Colonial_Pipeline_cyberattack'),
('Dakota Access Pipeline (DAPL)', 'United States', 'North America', 'pipeline', 'intact', 44.0000, -100.0000, 'Carries Bakken shale oil from North Dakota to Illinois. 570,000 bpd.', '2016-10-20', 'Major protest at Standing Rock Sioux reservation 2016-2017; Army Corps permit disputes. Legal battles over environmental review ongoing.', 'https://en.wikipedia.org/wiki/Dakota_Access_Pipeline'),
('Enbridge Line 5 (Great Lakes)', 'United States', 'North America', 'pipeline', 'intact', 46.0000, -84.5000, 'Carries Canadian oil under Straits of Mackinac connecting Lakes Michigan and Huron. 540,000 bpd. 71 years old.', '', 'Michigan governor ordered shutdown 2020; blocked by Enbridge in courts. Major environmental and legal dispute over aging pipeline under Great Lakes narrows.', 'https://en.wikipedia.org/wiki/Enbridge_Line_5'),
('Trans Mountain Pipeline (TMX)', 'Canada', 'North America', 'pipeline', 'intact', 53.0000, -120.0000, 'Carries Alberta oil sands to BC coast for export to Asia. 890,000 bpd (expanded). 1,147km. Completed 2024.', '', 'Expanded line tripled original capacity, completed May 2024 after decade of legal/Indigenous protests. Canada''s first new pipeline to Pacific coast in decades.', 'https://en.wikipedia.org/wiki/Trans_Mountain_Pipeline'),
('Enbridge Mainline System', 'Canada', 'North America', 'pipeline', 'intact', 52.0000, -105.0000, 'World''s longest crude oil pipeline network. Carries Canadian oil sands to US Midwest. 3 million bpd total system capacity.', '', 'Operational since 1950s. World''s largest petroleum pipeline system by volume transported.', 'https://en.wikipedia.org/wiki/Enbridge_Mainline'),
('Alliance Pipeline (Canada-US Gas)', 'Canada', 'North America', 'pipeline', 'intact', 53.5000, -110.0000, 'Carries natural gas from Fort St. John, BC to Illinois hub. 1.6 bcf/day. 3,848km.', '', 'Operational since 2000. Key Canadian gas export route to US markets.', ''),
('NOVA Gas Transmission (NGTL)', 'Canada', 'North America', 'pipeline', 'intact', 54.0000, -115.0000, 'Alberta provincial gas pipeline network. 24,600km. Key gathering/transport network for Western Canadian gas.', '', 'World''s third largest gas transmission network. Feeds all Canadian and US export pipelines from Alberta.', ''),
('Transcontinental Gas Pipeline (Transco)', 'United States', 'North America', 'pipeline', 'intact', 37.0000, -77.0000, 'Longest US natural gas pipeline, 1,800 miles from Gulf of Mexico to New York City. 17.5 bcf/day.', '', 'Operational since 1950. Carries 15% of US natural gas consumption. Key Northeast heating supply.', 'https://en.wikipedia.org/wiki/Transcontinental_Gas_Pipe_Line'),
('Tennessee Gas Pipeline', 'United States', 'North America', 'pipeline', 'intact', 41.0000, -74.0000, 'Major US gas pipeline from Gulf Coast to Northeast. 11,900 miles total system. 7 bcf/day.', '', 'Key supply route for New England states. Running at near full capacity winter peaks.', ''),
('Rockies Express Pipeline', 'United States', 'North America', 'pipeline', 'intact', 41.0000, -105.0000, 'Carries Rocky Mountain gas east to Midwest and Appalachian markets. 1,800 miles. 1.8 bcf/day.', '', 'Operational since 2009. Carries Rockies basin gas to eastern demand centers.', ''),
('Sabine Pass LNG Export Terminal (Pipelines)', 'United States', 'North America', 'pipeline', 'intact', 29.7300, -93.8700, 'Largest US LNG export terminal complex in Louisiana. Feed gas pipelines from multiple interstate systems. 45 mtpa total capacity with expansions.', '', 'First major US LNG export facility. Critical infrastructure for US LNG exports to Europe replacing Russian supplies.', 'https://en.wikipedia.org/wiki/Sabine_Pass_LNG_terminal'),
('Freeport LNG Terminal (Pipelines)', 'United States', 'North America', 'pipeline', 'damaged', 28.9800, -95.3600, 'Major US LNG export terminal on Quintana Island, Texas. 15 mtpa capacity.', '2022-06-08', 'Explosion and fire June 2022 shut facility for 8 months. Contributed to European gas supply crisis winter 2022. Restarted February 2023.', 'https://en.wikipedia.org/wiki/Freeport_LNG'),
('Mexico-Texas Natural Gas Pipelines (Sur de Texas-Tuxpan)', 'Mexico', 'North America', 'pipeline', 'intact', 22.5000, -97.5000, 'Offshore pipeline carrying US gas from Texas to Mexico''s Gulf Coast. 10.4 bcf/day capacity. 715km.', '', 'Operational since 2019. Critical for Mexico''s gas supply as domestic production declines.', ''),
('Pemex Gas Pipeline Network (Mexico)', 'Mexico', 'North America', 'pipeline', 'damaged', 19.5000, -96.5000, 'State-owned Pemex gas pipeline network across Mexico. Multiple compressor stations and trunk lines.', '2021-07-06', 'Major offshore Campeche Sound gas pipeline fire July 2021 caused "eye of fire" viral video. Multiple corrosion incidents across aging network.', ''),

-- ======================================================
-- SOUTH AMERICA
-- ======================================================
('TBG Pipeline (Brazil-Bolivia Gas)', 'Brazil', 'South America', 'pipeline', 'intact', -18.0000, -57.0000, 'Bolivia-Brazil gas pipeline (GASBOL). Carries Bolivian gas to São Paulo. 3,150km. 30 mmcm/day capacity.', '', 'Operational since 1999. Bolivia''s main gas export. Critical supply for southeastern Brazil including São Paulo industrial region.', 'https://en.wikipedia.org/wiki/Bolivia-Brazil_pipeline'),
('OPAL Pipeline (Venezuela-Colombia)', 'Venezuela', 'South America', 'pipeline', 'damaged', 8.0000, -67.0000, 'Venezuelan oil pipeline network (PDVSA). Multiple trunk lines from Orinoco Belt fields to Maracaibo terminals and refineries.', '2021-01-01', 'PDVSA pipelines severely degraded due to sanctions, lack of maintenance, and mismanagement. Multiple spills annually. Production collapsed from 3.2 mbpd (1998) to under 0.8 mbpd.', ''),
('Oleoducto Trasandino (OTA) Colombia-Ecuador', 'Colombia', 'South America', 'pipeline', 'damaged', 1.0000, -77.5000, 'Trans-Andean oil pipeline from Colombian Amazon fields to Pacific Coast. 500km.', '2023-04-20', 'ELN guerrilla group repeatedly bombs pipeline. 120+ attacks 2023-2024. Ecuador declared force majeure multiple times due to bombings.', ''),
('OCP Ecuador Heavy Oil Pipeline', 'Ecuador', 'South America', 'pipeline', 'intact', -1.0000, -78.0000, 'Heavy crude pipeline crossing Andes from Amazonian fields to Esmeraldas export terminal on Pacific. 450km. 450,000 bpd.', '', 'Operational since 2003. Ecuador''s main crude export pipeline.', ''),
('Gasoducto del Norte (Argentina-Bolivia)', 'Argentina', 'South America', 'pipeline', 'intact', -23.0000, -65.0000, 'Carries Bolivian gas south through Argentina. Key supply line for northern Argentina.', '', 'Operational. Bolivia gas flows declining as production falls.', ''),
('TGS/TGN Gas Pipeline Networks (Argentina)', 'Argentina', 'South America', 'pipeline', 'intact', -36.0000, -64.0000, 'Argentina''s main natural gas transmission networks (Transportadora de Gas del Sur / Norte). 28,000km total. Supply Patagonian gas north to Buenos Aires.', '', 'Critical for Argentine domestic gas supply and exports to Chile/Brazil/Uruguay.', ''),
('CAMISEA Pipeline System (Peru)', 'Peru', 'South America', 'pipeline', 'intact', -13.0000, -73.0000, 'Pipeline from Camisea gas field in Amazon to Lima coast. 730km. Peru''s main gas supply and LNG export feedstock.', '', 'Operational since 2004. Feeds Peru LNG export plant at Pampa Melchorita.', ''),

-- ======================================================
-- AFRICA
-- ======================================================
('Trans-Saharan Gas Pipeline (TSGP) - Planned', 'Nigeria', 'Africa', 'pipeline', 'intact', 20.0000, 10.0000, 'Proposed 4,128km pipeline from Nigeria through Niger and Algeria to Europe. 30 bcm/year. Called "Trans-African Pipeline."', '', 'Long-planned but repeatedly delayed by security, funding, and political issues. Niger coup 2023 further complicated project.', 'https://en.wikipedia.org/wiki/Trans-Saharan_gas_pipeline'),
('Niger Delta Oil Pipeline Network (NNPC/Shell)', 'Nigeria', 'Africa', 'pipeline', 'damaged', 5.5000, 5.8000, 'Extensive network of oil and gas pipelines across Niger Delta. Multiple trunk lines to export terminals.', '2024-03-15', 'Ongoing militant attacks, bunkering theft, and sabotage across network. Shell sold onshore assets 2024 due to unmanageable security situation. Millions of barrels lost to theft annually.', 'https://en.wikipedia.org/wiki/Niger_Delta_oil_spill'),
('West African Gas Pipeline (WAGP)', 'Nigeria', 'Africa', 'pipeline', 'damaged', 5.8000, 1.5000, 'Offshore pipeline carrying Nigerian gas to Benin, Togo, and Ghana. 678km. 170 mmcf/day.', '2023-05-20', 'Multiple disruptions from upstream attacks in Niger Delta and operational issues. Ghana faced repeated gas shortages and power outages.', 'https://en.wikipedia.org/wiki/West_African_Gas_Pipeline'),
('Chad-Cameroon Pipeline', 'Chad', 'Africa', 'pipeline', 'intact', 9.0000, 15.0000, 'Oil pipeline from landlocked Chad''s Doba basin to Cameroon''s Kribi port. 1,070km. 250,000 bpd.', '', 'Operational since 2003. World Bank-financed project. Chad''s main source of oil export revenue.', 'https://en.wikipedia.org/wiki/Chad%E2%80%93Cameroon_Pipeline'),
('EACOP (East Africa Crude Oil Pipeline)', 'Uganda', 'Africa', 'pipeline', 'intact', -1.5000, 33.0000, 'Proposed 1,445km heated pipeline from Uganda''s Lake Albert oilfields to Tanzanian Indian Ocean port. 216,000 bpd. World''s longest heated oil pipeline when built.', '', 'Under construction 2024. Massive human rights and environmental controversy. EU threatened sanctions. First oil expected 2025-2026.', 'https://en.wikipedia.org/wiki/East_African_Crude_Oil_Pipeline'),
('Hassi R''Mel Gas Complex (Algeria)', 'Algeria', 'Africa', 'pipeline', 'intact', 32.9000, 3.1000, 'World''s largest natural gas liquids complex and Algeria''s main gas hub. Central node for all export pipelines to Europe.', '2013-01-16', 'Al-Qaeda affiliated Mokhtar Belmokhtar seized nearby In Amenas gas facility Jan 2013; 40 hostages killed. Hassi R''Mel itself secured.', 'https://en.wikipedia.org/wiki/In_Amenas_hostage_crisis'),
('In Salah Gas Pipeline (Algeria)', 'Algeria', 'Africa', 'pipeline', 'intact', 27.2000, 2.5000, 'Pipeline network from In Salah gas fields in central Algerian Sahara to northern treatment plants and export terminals.', '', 'Critical mid-Saharan gas production hub feeding European export pipelines.', ''),
('Greenstream Pipeline (Libya-Italy)', 'Libya', 'Africa', 'pipeline', 'damaged', 33.5000, 12.5000, 'Offshore pipeline from Mellitah gas complex, Libya to Gela, Sicily. 520km. 11 bcm/year.', '2022-07-01', 'Flows repeatedly interrupted by Libyan political instability, force majeure declarations, and rival faction control of upstream fields. Major Libyan export route when operating.', 'https://en.wikipedia.org/wiki/Greenstream_pipeline'),
('Egypt Gas Export Pipeline (GASCO)', 'Egypt', 'North Africa', 'pipeline', 'intact', 30.0000, 30.5000, 'Egypt''s main gas transmission and export network. Includes East Mediterranean Gas (EMG) to Israel and connections to Arab Gas Pipeline.', '', 'Egypt became major gas exporter after Zohr deepwater field discovery 2015. Gas now flows from Israel to Egypt for LNG export.', ''),
('Mozambique LNG Pipeline (Rovuma)', 'Mozambique', 'Africa', 'pipeline', 'intact', -13.0000, 40.5000, 'Pipeline from Rovuma Basin offshore gas fields to Cabo Delgado LNG plant.', '2021-04-24', 'TotalEnergies suspended construction of Area 1 LNG project April 2021 following Islamist insurgency in Cabo Delgado province. Security improved; project being revived 2024.', ''),
('Transmed extension to Libya (Greenstream 2)', 'Libya', 'Africa', 'pipeline', 'intact', 32.0000, 15.0000, 'Western Libya gas gathering pipelines feeding Mellitah processing complex and Greenstream export line.', '', 'Multiple competing militias control different pipeline sections. Ongoing export disruptions.', ''),

-- ======================================================
-- MIDDLE EAST (Additional)
-- ======================================================
('Qatar-Bahrain Undersea Gas Pipeline', 'Qatar', 'Middle East', 'pipeline', 'intact', 26.0000, 50.5000, 'Dolphin Pipeline spur serving Bahrain with Qatari gas under the Gulf.', '', 'Operational. Bahrain dependent on Qatari gas through this line.', ''),
('Dolphin Gas Project (Qatar-UAE-Oman)', 'Qatar', 'Middle East', 'pipeline', 'intact', 25.5000, 55.0000, 'Subsea pipeline carrying Qatari North Field gas to UAE and Oman. 3.2 bcf/day. First cross-border Gulf gas line.', '', 'Operational since 2007. UAE''s main gas import, reducing dependence on own shrinking reserves.', 'https://en.wikipedia.org/wiki/Dolphin_Energy'),
('Abu Dhabi Crude Oil Pipeline (ADCO)', 'UAE', 'Middle East', 'pipeline', 'intact', 24.0000, 54.5000, 'Multiple oil pipelines from Abu Dhabi onshore fields to export terminals at Ruwais and Fujairah. 1.8 million bpd.', '', 'Strategic Fujairah terminal on Gulf of Oman allows UAE exports bypassing Strait of Hormuz.', ''),
('UAE Fujairah Bypass Pipeline', 'UAE', 'Middle East', 'pipeline', 'intact', 23.8000, 56.5000, 'ADCO pipeline from Habshan oilfield to Fujairah port on Arabian Sea coast. 1.5 million bpd. 400km. Bypasses Strait of Hormuz.', '', 'Key strategic asset allowing UAE to export crude without transiting Strait of Hormuz.', ''),
('Saudi-Bahrain Crude Pipeline (BAPCO)', 'Saudi Arabia', 'Middle East', 'pipeline', 'intact', 26.2000, 50.4000, 'Pipeline from Saudi Aramco''s Abu Safah field to Bahrain''s Sitra refinery. 350,000 bpd. Undersea causeway route.', '', 'Saudi Arabia supplies Bahrain''s domestic oil consumption through this pipeline.', ''),
('Iraq-Turkey Pipeline (Kirkuk-Ceyhan) - Northern Section', 'Turkey', 'Middle East', 'pipeline', 'damaged', 37.5000, 39.0000, 'Turkish section of Iraq-Turkey crude pipeline from Iraqi border to Ceyhan Mediterranean export terminal.', '2023-03-22', 'International arbitration ruling March 2023 resulted in Turkey halting Iraqi Kurdistan exports. 400,000 bpd of KRG oil blocked for over a year. Partial resumption negotiations ongoing.', ''),
('Iraq Southern Export Pipeline (Basra)', 'Iraq', 'Middle East', 'pipeline', 'intact', 29.5000, 48.0000, 'Multiple offshore loading buoys and pipeline network for southern Iraq oil exports from Basra Oil Terminal. 3.5 million bpd.', '', 'Iraq''s main export channel. Critical Gulf loading infrastructure.', ''),
('South Pars/North Dome Gas Condensate Field Pipelines', 'Iran', 'Middle East', 'pipeline', 'intact', 27.5000, 52.5000, 'Massive pipeline network from world''s largest gas field (shared with Qatar) to Iranian coast and domestic distribution. 700 mmcm/day.', '', 'Critical Iranian gas infrastructure. Pipelines to domestic consumption and potential export (currently sanctioned).', 'https://en.wikipedia.org/wiki/South_Pars_/_North_Dome_Gas-Condensate_field'),
('Pan-Arab Pipeline (Proposed extension)', 'Syria', 'Middle East', 'pipeline', 'destroyed', 34.5000, 36.5000, 'Iran-Iraq-Syria pipeline proposal (Islamic Gas Pipeline). Would carry Iranian gas through Iraq and Syria to Lebanon/Mediterranean.', '2014-03-01', 'Syrian war effectively killed the project. Existing Arab Gas Pipeline infrastructure in Syria largely destroyed in civil war.', ''),
('Iran-Pakistan Gas Pipeline (IP Pipeline)', 'Iran', 'Middle East', 'pipeline', 'intact', 27.5000, 62.0000, 'Proposed pipeline from Iran''s South Pars field to Pakistan''s Sindh province. 1,900km. 21.5 bcm/year.', '', 'Iranian section largely built; Pakistan section stalled due to US sanctions threats. Pakistan ordered to pay Iran billions in arbitration for failure to complete its section.', 'https://en.wikipedia.org/wiki/Iran%E2%80%93Pakistan_gas_pipeline'),

-- ======================================================
-- ASIA-PACIFIC
-- ======================================================
('Siberia-China Gas Pipeline (Power of Siberia)', 'China', 'East Asia', 'pipeline', 'intact', 48.5000, 127.0000, 'Chinese receiving end of Russia''s Power of Siberia pipeline. Distributes Russian gas through Northeast China (Heilongjiang, Jilin).', '', 'Operational since 2019. China is now Russia''s largest gas export customer following European demand collapse.', ''),
('West-East Gas Pipeline System (China)', 'China', 'East Asia', 'pipeline', 'intact', 36.0000, 102.0000, 'China''s massive internal gas pipeline network. Lines I-IV carry gas from Xinjiang (and Central Asia via CAGP) to Shanghai and eastern coast. 40 bcm/year.', '', 'Operational since 2004-2016 (four lines). Critical domestic energy infrastructure distributing Turkmen and Sichuan gas.', 'https://en.wikipedia.org/wiki/West%E2%80%93East_Gas_Pipeline'),
('Sichuan-to-East Gas Pipeline (China)', 'China', 'East Asia', 'pipeline', 'intact', 30.5000, 107.0000, 'Carries Sichuan basin shale and conventional gas eastward to Yangtze River delta. Key domestic Chinese pipeline.', '', 'Operational since 2010s. Sichuan basin is China''s largest domestic gas production area.', ''),
('Myanmar-China Oil Pipeline', 'Myanmar', 'Southeast Asia', 'pipeline', 'intact', 22.0000, 97.0000, 'Twin oil and gas pipelines from Kyaukphyu deep-sea port in Myanmar through Myanmar to Kunming, China. 440,000 bpd oil; 12 bcm/year gas.', '', 'Operational since 2013-2017. Allows China to import Middle East crude bypassing Strait of Malacca. Strategic bypass route.', 'https://en.wikipedia.org/wiki/Sino-Myanmar_pipelines'),
('Kazakhstan-China Oil Pipeline (Atyrau-Alashankou)', 'China', 'East Asia', 'pipeline', 'intact', 45.0000, 82.0000, 'Chinese receiving end of Kazakhstan-China crude pipeline into Xinjiang. Connects to domestic PetroChina network.', '', 'Operational since 2006. China''s overland oil import route from Central Asia.', ''),
('Minas/Duri Field Pipelines (Indonesia)', 'Indonesia', 'Southeast Asia', 'pipeline', 'intact', 1.0000, 101.5000, 'Chevron/KKKS pipeline network from Sumatra''s Minas/Duri oilfields to Dumai export terminal. 125,000 bpd.', '', 'Operational since 1970s. Sumatra''s main oil export infrastructure.', ''),
('Natuna Gas Pipeline (Indonesia-Singapore)', 'Indonesia', 'Southeast Asia', 'pipeline', 'intact', 2.5000, 107.5000, 'Pipeline carrying Indonesian gas from West Natuna Sea to Singapore and Batam. Critical Singapore gas supply.', '', 'Operational since 2001. Singapore''s main piped gas import.', ''),
('Thailand Gas Pipeline Network (PTT)', 'Thailand', 'Southeast Asia', 'pipeline', 'intact', 11.5000, 100.0000, 'PTT''s gas pipeline network from Gulf of Thailand offshore fields to onshore power plants and industrial users. Multiple offshore-to-shore lines.', '', 'Operational. Thailand''s main energy infrastructure.', ''),
('Australia Northwest Shelf Pipelines (Karratha)', 'Australia', 'Asia-Pacific', 'pipeline', 'intact', -20.5000, 116.5000, 'Woodside and partners'' pipeline network from North West Shelf LNG platforms offshore WA to Karratha and Dampier LNG plants.', '', 'World''s largest LNG export hub. Woodside, Chevron (Gorgon, Wheatstone) pipelines to shore.', ''),
('Dampier-to-Bunbury Gas Pipeline (DBNGP)', 'Australia', 'Asia-Pacific', 'pipeline', 'intact', -26.0000, 117.0000, 'Australia''s longest gas pipeline. 1,530km from Dampier on North West Shelf to Perth/Bunbury. Supplies 60% of WA''s gas.', '', 'Critical Western Australia energy infrastructure. Operational since 1984.', ''),
('Eastern Gas Pipeline (Australia)', 'Australia', 'Asia-Pacific', 'pipeline', 'intact', -35.0000, 149.0000, 'Jemena-owned pipeline from Longford, Victoria to Sydney/ACT. 800km. Critical Eastern Australia gas supply.', '', 'Operational since 2000. Key route for Bass Strait gas to NSW.', ''),
('Japan LNG Import Terminals (Tokyo Bay)', 'Japan', 'East Asia', 'pipeline', 'intact', 35.4500, 139.7500, 'Tokyo Gas/TEPCO LNG import and regasification terminals in Tokyo Bay feeding high-pressure gas transmission network across Kanto.', '', 'Japan''s largest LNG demand center. Multiple competing terminal operators.', ''),
('South Korea LNG Import Infrastructure (Pyeongtaek)', 'South Korea', 'East Asia', 'pipeline', 'intact', 36.9500, 127.1000, 'KOGAS main LNG import terminal at Pyeongtaek feeding Korean gas transmission grid. 60+ mtpa national import capacity.', '', 'World''s second largest LNG importer. Critical national energy security infrastructure.', ''),
('India-Bangladesh Gas Pipeline', 'India', 'South Asia', 'pipeline', 'intact', 23.5000, 88.5000, 'India-Bangladesh Friendship Pipeline carrying Indian gas to Bangladesh. 5 mmcm/day. 130km.', '', 'Operational since 2023. First gas import for Bangladesh from India. Bangladesh facing acute gas shortages.', ''),
('Rajasthan-Salaya Oil Pipeline (India)', 'India', 'South Asia', 'pipeline', 'intact', 26.0000, 71.0000, 'Cairn Oil & Gas pipeline from Mangala field in Rajasthan to Gujarat refineries. 670km. 175,000 bpd.', '', 'Operational since 2009. India''s first modern crude pipeline from desert oil discovery.', ''),
('Hazira-Vijaipur-Jagdishpur (HVJ) Gas Pipeline India', 'India', 'South Asia', 'pipeline', 'intact', 22.5000, 76.0000, 'GAIL''s main gas transmission trunk line from Gujarat coast to UP. 1,750km. Backbone of Indian gas grid.', '', 'Operational since 1987. India''s main gas pipeline. Feeds fertilizer plants and power stations across North India.', ''),

-- ======================================================
-- STRATEGIC CHOKEPOINTS & OFFSHORE
-- ======================================================
('Strait of Malacca Oil Transit (Tanker Route)', 'Malaysia', 'Southeast Asia', 'highway', 'intact', 2.5000, 102.0000, 'Narrow sea lane between Malaysian Peninsula and Sumatra. 15.7 million bpd tanker transit daily. World''s busiest shipping chokepoint after Strait of Hormuz.', '', 'Any blockage would force 3,200km detour around Lombok/Sunda Strait. China imports 80% of oil through here.', 'https://en.wikipedia.org/wiki/Strait_of_Malacca'),
('Cape of Good Hope Route (Oil Diversion)', 'South Africa', 'Africa', 'highway', 'intact', -34.3568, 18.4733, 'Alternative oil tanker route around southern Africa, bypassing Suez Canal and Red Sea. 12,000 extra miles vs. Suez.', '2023-10-16', 'Houthi Red Sea attacks from October 2023 caused over 400 vessels/month to divert around Cape, massively increasing shipping costs and journey times.', ''),
('Lombok Strait Oil Route (Indonesia)', 'Indonesia', 'Southeast Asia', 'highway', 'intact', -8.7500, 115.7500, 'Deepwater strait between Bali and Lombok islands. Used by large supertankers too large for Malacca Strait. Key backup route.', '', 'Second alternative to Malacca for very large crude carriers (VLCCs). Critical for Asia-Pacific energy security.', ''),
('Baltic Sea LNG Route (FSRUs)', 'Germany', 'Europe', 'pipeline', 'intact', 54.5000, 11.5000, 'German floating LNG import terminals (FSRUs) installed at Brunsbüttel, Wilhelmshaven, Lubmin, Mukran. 17 bcm/year total capacity.', '', 'Emergency LNG infrastructure built in 2022-2023 following Nord Stream sabotage and Russian supply cutoff. Critical European gas security.', ''),
('US Gulf Coast LNG Export Hub (Total)', 'United States', 'North America', 'pipeline', 'intact', 29.5000, -93.5000, 'Combined US LNG export capacity from all Gulf Coast terminals (Sabine Pass, Corpus Christi, Calcasieu Pass, Freeport, Lake Charles). 80+ mtpa.', '', 'US became world''s largest LNG exporter in 2023. Filling gap left by Russian pipeline gas cutoff to Europe. Critical Western energy security infrastructure.', ''),
('Mozambique-Tanzania LNG Route (Coral FLNG)', 'Mozambique', 'Africa', 'pipeline', 'intact', -15.5000, 40.6000, 'ENI-operated Coral South FLNG vessel above Rovuma offshore gas field. First African deep-water FLNG. 3.4 mtpa.', '', 'First production 2022. Symbol of African LNG frontier development.', ''),
('Papua New Guinea LNG Pipeline (PNG LNG)', 'Papua New Guinea', 'Asia-Pacific', 'pipeline', 'intact', -6.5000, 144.0000, 'ExxonMobil PNG LNG project. 700km pipeline from Hides gas field through Highlands to Port Moresby and LNG plant. 8.25 mtpa.', '', 'Operational since 2014. PNG''s largest industrial project. Supplies Asian LNG markets.', '');
